import Presentation from '@/components/Presentation'
import Head from 'next/head'
import About from '@/components/about'
import Skills from '@/components/skills'
import Projects from '@/components/projects'
import Contact from '@/components/contact'
import HCaptcha from '@hcaptcha/react-hcaptcha';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Florian Broeks | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://js.hcaptcha.com/1/api.js" async defer></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Presentation/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact>
        <HCaptcha
          sitekey="a7c48552-a7dd-472e-be71-e087d28ab5cd"
          onVerify={(token,ekey) => handleVerificationSuccess(token, ekey)}
        />
      </Contact>
    </div>
  )
}
